### ISSUE TITLE
tempfile.tif: Cannot read TIFF header.

### ISSUE THREAD

**Issue by morris0824** [rezazad68/BCDU-Net#11]
I tried to run "python prepare_datasets_DRIVE.py" and got the error.

original image: 21_training.tif
tempfile.tif: Cannot read TIFF header.
Traceback (most recent call last):
  File "prepare_datasets_DRIVE.py", line 82, in <module>
    imgs_train, groundTruth_train, border_masks_train = get_datasets(original_imgs_train,groundTruth_imgs_train,borderMasks_imgs_train,"train")
  File "prepare_datasets_DRIVE.py", line 46, in get_datasets
    imgs[i] = np.asarray(img)
TypeError: float() argument must be a string or a number, not 'TiffImageFile'

**Comment by morris0824** [comment]
Sorry, I found where is the problem.
I installed the libtiff=4.1.0.
After downgrade into 4.0.10, it is ok now.
